spring:
  application:
    name: system-analysis-design

  datasource:
    url: jdbc:mysql://localhost:3306/SystemAD
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG